#!/usr/bin/env bash
#Command script to run on all nodes as Azure Batch node start task, to install prerequisites etc.
apt-get update
apt-get install nfs-kernel-server
apt-get install nfs-common
apt-get install rpcbind
systemctl enable rpcbind
systemctl enable nfs-kernel-server
apt-get -y install openmpi-bin openmpi-common openssh-client openssh-server
sed -i -e 's/Defaults    requiretty.*/ #Defaults    requiretty/g' /etc/sudoers
apt-get install mmv
service nfs-kernel-server start
